language: cpp

env:
  - LD_RUN_PATH=lib64

install:
  - sudo add-apt-repository -y ppa:codegear/release
  - sudo wget -q -O- http://archive.getdeb.net/getdeb-archive.key | sudo apt-key add -
  - sudo sh -c "echo 'deb http://archive.getdeb.net/ubuntu/ precise-getdeb games' >> /etc/apt/sources.list"
  - sudo apt-get update -qq
  - sudo apt-get install -qq premake4 libfreetype6-dev libevent-dev libsqlite3-dev liblua5.2-dev libxxf86vm-dev libirrlicht1.8-dev
  - sudo ln -s /usr/lib/x86_64-linux-gnu/liblua5.2.so /usr/lib/liblua.so
  - sudo ln -s /usr/include/irrlicht1.8 /usr/include/irrlicht
  - wget -q http://www.ambiera.at/downloads/irrKlang-64bit-1.5.0.zip
  - unzip -q irrKlang-64bit-1.5.0.zip
  - ln -s irrKlang-64bit-1.5.0 irrKlang-1.5.0
  - sudo cp irrKlang-64bit-1.5.0/bin/linux-gcc-64/libIrrKlang.so /usr/lib/libirrKlang.so

script:
  - premake4 gmake
  - make config=release -C build

after_success:
  - mkdir lib64
  - strip bin/release/*
  - cp bin/release/ygopro .
  - cp bin/release/libocgcore.so lib64
  - cp irrKlang-64bit-1.5.0/bin/linux-gcc-64/ikpMP3.so ikpMP3-64.so
  - cp /lib/x86_64-linux-gnu/libpng12.so.0 lib64
  - cp /usr/lib/libevent_core-2.0.so.5 lib64
  - cp /usr/lib/libevent_pthreads-2.0.so.5 lib64
  - cp /usr/lib/libirrKlang.so lib64
  - cp /usr/lib/x86_64-linux-gnu/libIrrlicht.so.1.8 lib64
  - cp /usr/lib/x86_64-linux-gnu/libfreetype.so.6 lib64
  - cp /usr/lib/x86_64-linux-gnu/libjpeg.so.8 lib64
  - ldd ygopro

deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: MJds1zsu7yWWcSu9B+MaVtVVw/ZeuOGUMUa812iVaHOHdfPRwq7PZh2vyz3yHonfzJ6bvk1CFx5jQTjtIfn7NlCtdYP8fZ6hiHh2lef+9eQOvQef3F3aB0jT4tpF7S4VsN9Y8A0djOHc7aamrP+d9GvadznRF6VvME8x+Fl4sCg=
  file:
    - ygopro
    - ikpMP3-64.so
    - lib64/libocgcore.so
    - lib64/libpng12.so.0
    - lib64/libevent_core-2.0.so.5
    - lib64/libevent_pthreads-2.0.so.5
    - lib64/libirrKlang.so
    - lib64/libIrrlicht.so.1.8
    - lib64/libfreetype.so.6
    - lib64/libjpeg.so.8
  on:
    repo: adrianojn/ygopro-salvation-custom
    branch: builder
  on:
    tags: true

