language: cpp

env:
  - LD_RUN_PATH=lib64

install:
  - sudo add-apt-repository -y ppa:codegear/release
  - sudo wget -q -O- http://archive.getdeb.net/getdeb-archive.key | sudo apt-key add -
  - sudo sh -c "echo 'deb http://archive.getdeb.net/ubuntu/ precise-getdeb games' >> /etc/apt/sources.list"
  - sudo apt-get update -qq
  - sudo apt-get install -qq premake4 libfreetype6-dev libevent-dev libsqlite3-dev liblua5.2-dev libxxf86vm-dev libirrlicht1.8-dev
  - sudo ln -s /usr/lib/x86_64-linux-gnu/liblua5.2.so /usr/lib/liblua.so
  - sudo ln -s /usr/include/irrlicht1.8 /usr/include/irrlicht
  - wget -q http://www.ambiera.at/downloads/irrKlang-64bit-1.5.0.zip
  - unzip -q irrKlang-64bit-1.5.0.zip
  - ln -s irrKlang-64bit-1.5.0 irrKlang-1.5.0
  - sudo cp irrKlang-64bit-1.5.0/bin/linux-gcc-64/libIrrKlang.so /usr/lib/libirrKlang.so

script:
  - premake4 gmake
  - make config=release -C build

after_success:
  - ldd bin/release/ygopro

